/**
 * 杭州生态物种数据库（60 组：30 动物 + 30 植物）
 * ------------------------------------------------------------------
 * 字段：id 唯一标识 / name 中文名 / latin 拉丁学名 / kind animal|plant
 *       emoji 兜底图标 / color 卡片主题色 / habitat 杭州栖息地
 *       status 保护或生态状态 / rarity 稀有度 1~5（影响得分）
 *       desc 科普介绍 / facts 冷知识 / query 图片检索兜底关键词
 * 真实图片由 js/images.js 的 window.SPECIES_IMAGES[id] 提供（已逐一视觉校验）。
 * ------------------------------------------------------------------
 */
const SPECIES = [
  // ================= 动 物 (1-30) =================
  { id:"egret", name:"白鹭", latin:"Egretta garzetta", kind:"animal", emoji:"🕊️", color:"#7fd8be",
    habitat:"西溪湿地、西湖沿岸浅滩", status:"国家“三有”保护动物", rarity:2,
    desc:"白鹭是杭州湿地最具代表性的水鸟，通体雪白，繁殖期头后生出细长饰羽。它们在浅水中踱步觅食，是水质与湿地健康的“活指标”。",
    facts:["飞行时颈部弯成 S 形，与鹤类的直颈不同","捕食时会用脚搅动淤泥惊起小鱼","西溪湿地记录到的鸟类超过 190 种"], query:"little egret bird" },
  { id:"mandarin", name:"鸳鸯", latin:"Aix galericulata", kind:"animal", emoji:"🦆", color:"#f2a65a",
    habitat:"西湖、太子湾、植物园水域", status:"国家二级保护动物", rarity:3,
    desc:"鸳鸯是西湖的明星水禽。雄鸟羽色绚烂、帆状飞羽高翘。近年西湖鸳鸯已能自然繁殖，成为城市生态改善的标志性事件。",
    facts:["雄鸟繁殖后“换羽”变得像雌鸟一样朴素","常在树洞筑巢，雏鸟出壳后需从高处跳下","西湖是国内少有的城市自然繁殖鸳鸯地"], query:"mandarin duck" },
  { id:"squirrel", name:"赤腹松鼠", latin:"Callosciurus erythraeus", kind:"animal", emoji:"🐿️", color:"#d98b6f",
    habitat:"植物园、九溪、灵隐林区", status:"常见本土物种", rarity:1,
    desc:"杭州樟树林与竹林间常见的小型松鼠，腹部橙红、尾巴蓬松。它们埋藏坚果的行为无意中帮助了森林树木的传播。",
    facts:["埋下却忘记挖出的坚果会长成新树","门齿终身生长，需要不停啃咬","会用尾巴摆动进行同伴间的信号交流"], query:"red-bellied squirrel" },
  { id:"sturgeon", name:"中华鲟", latin:"Acipenser sinensis", kind:"animal", emoji:"🐟", color:"#5b8fb9",
    habitat:"钱塘江洄游通道", status:"国家一级保护动物 · 极危", rarity:5,
    desc:"被称为“水中大熊猫”的古老洄游鱼类，曾溯钱塘江而上。它见证上亿年地质变迁，如今数量极稀，是江河生态保护的核心物种。",
    facts:["存在超过 1.4 亿年，与恐龙同期","可长到数百公斤、寿命数十年","钱塘江曾是其历史洄游产卵通道之一"], query:"chinese sturgeon" },
  { id:"pheasant", name:"白鹇", latin:"Lophura nycthemera", kind:"animal", emoji:"🐔", color:"#9aa7b0",
    habitat:"临安、天目山常绿阔叶林", status:"国家二级保护动物 · 浙江省鸟", rarity:4,
    desc:"白鹇雄鸟上体银白缀黑纹、长尾如瀑，行走优雅从容，古人称“林中君子”，是浙江省鸟，栖于杭州西部山林。",
    facts:["被李白写入诗中“白鹇白如锦”","雄鸟通过抖动羽毛与鸣叫求偶","对森林完整度要求高，是良好栖息地象征"], query:"silver pheasant" },
  { id:"beeeater", name:"蓝喉蜂虎", latin:"Merops viridis", kind:"animal", emoji:"🦜", color:"#48b5c4",
    habitat:"杭州近郊沙土崖壁", status:"国家二级保护动物", rarity:4,
    desc:"被誉为“中国最美小鸟”之一，羽色蓝绿相间、喉部宝蓝，善于空中捕食蜂与蜻蜓。近年在杭州周边繁殖，引来众多观鸟爱好者。",
    facts:["在沙质崖壁上挖洞筑巢","能在飞行中精准捕捉飞虫","捕到蜂后会摔打去除毒刺再吞食"], query:"blue-throated bee-eater" },
  { id:"grebe", name:"小䴙䴘", latin:"Tachybaptus ruficollis", kind:"animal", emoji:"🐤", color:"#8a7f6e",
    habitat:"西湖、西溪及各类静水池塘", status:"常见水鸟", rarity:1,
    desc:"体型小巧的潜水能手，几乎终年在水面活动。受惊时立刻潜入水下逃避，是杭州池塘与湖湾里最常见的“小水葫芦”。",
    facts:["脚长在身体后方，极擅潜水却不擅走路","会把雏鸟背在背上游动","繁殖期发出清亮的连串颤鸣"], query:"little grebe" },
  { id:"nightheron", name:"夜鹭", latin:"Nycticorax nycticorax", kind:"animal", emoji:"🐦", color:"#6b7a8f",
    habitat:"西湖、西溪林缘水域", status:"国家“三有”保护动物", rarity:2,
    desc:"体态敦实的灰黑色鹭，昼伏夜出。白天成群栖息在临水树上，黄昏后飞往浅滩捕鱼，是城市水域的“夜班渔夫”。",
    facts:["成鸟头顶与背为墨绿黑色，眼睛红色","幼鸟满身褐色纵纹，与成鸟差异极大","黄昏起飞时发出粗哑的“呱”声"], query:"black-crowned night heron" },
  { id:"pondheron", name:"池鹭", latin:"Ardeola bacchus", kind:"animal", emoji:"🐦", color:"#b08968",
    habitat:"稻田、荷塘、西溪浅水", status:"常见涉禽", rarity:1,
    desc:"繁殖期头颈栗红、背披蓝黑蓑羽，静立时貌不惊人，一旦振翅便露出雪白的双翼，是荷塘边极具反差感的涉禽。",
    facts:["飞行时翅膀纯白，落地后又“隐身”于草色","常单独站在荷叶或田埂上守株待兔","以小鱼、蛙、昆虫为食"], query:"chinese pond heron" },
  { id:"bulbul", name:"白头鹎", latin:"Pycnonotus sinensis", kind:"animal", emoji:"🐦", color:"#9fae7a",
    habitat:"公园、行道树、庭院", status:"常见留鸟", rarity:1,
    desc:"俗称“白头翁”，眼后一抹白斑十分醒目。适应力强、鸣声婉转，是杭州城市绿地里最常见、最爱歌唱的鸟之一。",
    facts:["得名于头后显眼的白色斑块","杂食性，爱吃浆果也吃昆虫","常成对或成小群在枝头喧闹"], query:"light-vented bulbul" },
  { id:"blackbird", name:"乌鸫", latin:"Turdus mandarinus", kind:"animal", emoji:"🐦‍⬛", color:"#5c5651",
    habitat:"草坪、绿地、行道树", status:"常见留鸟", rarity:1,
    desc:"通体乌黑、喙与眼圈橙黄的中型鸣禽，是杭州城市里的“歌唱家”。清晨常在高处婉转鸣唱，也会模仿其它鸟叫。",
    facts:["被誉为“中国的夜莺”，鸣声极富变化","常在草地上跳跃翻找蚯蚓","上海市市鸟即为乌鸫"], query:"chinese blackbird" },
  { id:"dove", name:"珠颈斑鸠", latin:"Spilopelia chinensis", kind:"animal", emoji:"🕊️", color:"#c2a68c",
    habitat:"城市庭院、公园、屋檐", status:"常见留鸟", rarity:1,
    desc:"颈侧一圈黑底白点如珍珠项链，因而得名。性情温顺、与人相邻而居，常在阳台与树杈上搭起简陋的巢。",
    facts:["颈部“珍珠项链”是识别关键","鸣声为低沉的“咕咕—咕”","巢极简单，常只是几根交叉的树枝"], query:"spotted dove" },
  { id:"kingfisher", name:"普通翠鸟", latin:"Alcedo atthis", kind:"animal", emoji:"🐦", color:"#2ca6a4",
    habitat:"西湖、西溪、溪流岸边", status:"国家“三有”保护动物", rarity:2,
    desc:"背羽宝蓝、腹部橙红的小型翠鸟，常静立枝头俯瞰水面，一旦锁定小鱼便如蓝色闪电般俯冲入水，被称为“水上翡翠”。",
    facts:["俯冲入水捕鱼命中率极高","羽色源于结构色而非色素","在土质河岸掘洞筑巢"], query:"common kingfisher" },
  { id:"wagtail", name:"白鹡鸰", latin:"Motacilla alba", kind:"animal", emoji:"🐦", color:"#a7b0b8",
    habitat:"水岸、湿地、开阔草地", status:"常见鸟类", rarity:1,
    desc:"黑白分明的小鸟，走动时尾巴不停上下摆动，飞行呈波浪状。常在西湖岸边、停车场等开阔地面小步疾走觅食。",
    facts:["停歇时尾羽不停上下点动，得名“点水雀”","飞行轨迹呈波浪形并伴清脆叫声","喜在人类活动的开阔地面觅食"], query:"white wagtail" },
  { id:"moorhen", name:"黑水鸡", latin:"Gallinula chloropus", kind:"animal", emoji:"🐔", color:"#4f5d63",
    habitat:"荷塘、西溪、静水湿地", status:"常见水鸟", rarity:1,
    desc:"全身黑褐、额甲鲜红的中型水禽，游动时头颈一点一点向前伸缩。常在荷叶与芦苇间穿行，是杭州湿地的常住居民。",
    facts:["鲜红的额甲是最醒目的识别特征","脚趾细长，能在浮叶上行走","幼鸟会帮父母照看后一窝弟妹"], query:"common moorhen" },
  { id:"coot", name:"白骨顶", latin:"Fulica atra", kind:"animal", emoji:"🦆", color:"#3f4a52",
    habitat:"西湖、西溪开阔水面", status:"常见水鸟", rarity:1,
    desc:"通体炭黑、额甲雪白的水鸡，成群在开阔水面游弋、潜水取食水草。冬季常在西湖聚成大群，是易见的越冬水鸟。",
    facts:["白色额甲与黑水鸡的红额甲正好相反","趾边有瓣蹼，划水潜水皆能","起飞前需在水面助跑一段"], query:"eurasian coot" },
  { id:"hoopoe", name:"戴胜", latin:"Upupa epops", kind:"animal", emoji:"🐦", color:"#c99a5b",
    habitat:"开阔草地、林缘、农田", status:"国家“三有”保护动物", rarity:2,
    desc:"头顶一把可开合的羽冠、身披黑白斑纹、喙细长下弯，造型古典。在草地上边走边用长喙探土捕食虫蛹。",
    facts:["受惊或降落时会展开扇形羽冠","以色列的国鸟","用细长的喙在土中探寻幼虫"], query:"eurasian hoopoe" },
  { id:"greattit", name:"大山雀", latin:"Parus minor", kind:"animal", emoji:"🐦", color:"#7f8fa0",
    habitat:"公园、林地、庭院", status:"常见留鸟", rarity:1,
    desc:"黑头白颊、胸腹中央一道黑色纵带的活泼小鸟。鸣声清亮多变，常倒挂枝头觅食，是城市林地的常见成员。",
    facts:["胸前的黑色纵带越宽往往越强壮","叫声被形容为“子—子—黑”","冬季常与其它小鸟混群活动"], query:"great tit bird" },
  { id:"azuremagpie", name:"灰喜鹊", latin:"Cyanopica cyanus", kind:"animal", emoji:"🐦", color:"#8fb0c9",
    habitat:"公园、行道树、林地", status:"常见留鸟", rarity:1,
    desc:"头黑、背灰、翅与长尾呈优雅的天蓝色，常成小群喧闹穿梭于树冠间，是杭州绿地里颜值颇高的鸦科鸟类。",
    facts:["翅与尾的天蓝色十分独特","成群活动，遇天敌会集体驱赶","杂食且机警，适应城市环境"], query:"azure-winged magpie" },
  { id:"magpie", name:"喜鹊", latin:"Pica serica", kind:"animal", emoji:"🐦", color:"#4c5566",
    habitat:"城郊、田野、行道树", status:"常见留鸟", rarity:1,
    desc:"黑白分明、尾长带金属光泽的大型鸣禽，民间视为吉祥之鸟。在高大乔木顶端筑起显眼的大型球状巢。",
    facts:["“喜鹊报喜”是流传千年的民俗意象","智力较高，能识别镜中的自己","巢为带顶盖的大型球状结构"], query:"oriental magpie" },
  { id:"starling", name:"黑领椋鸟", latin:"Gracupica nigricollis", kind:"animal", emoji:"🐦", color:"#8a8f94",
    habitat:"农田、草坪、开阔绿地", status:"常见留鸟", rarity:2,
    desc:"白头配一圈黑色颈环，眼周裸皮鲜黄，体态挺拔。常成对在草地上大步觅食，鸣声嘹亮，是南方开阔地的典型椋鸟。",
    facts:["黑色的“颈圈”是识别关键","会在高压电塔上筑大型草巢","杂食，尤爱在翻耕的土地上找虫"], query:"black-collared starling" },
  { id:"mallard", name:"绿头鸭", latin:"Anas platyrhynchos", kind:"animal", emoji:"🦆", color:"#5f8f4e",
    habitat:"西湖、西溪、城市河道", status:"常见水鸭", rarity:1,
    desc:"雄鸭头颈亮绿、颈环雪白，是最广为人知的野鸭，也是家鸭的祖先。常在城市水面成群游弋、翻身取食水底植物。",
    facts:["家鸭大多由绿头鸭驯化而来","取食时常头朝下、尾朝上倒立","雌雄羽色差异显著"], query:"mallard duck" },
  { id:"weasel", name:"黄鼬", latin:"Mustela sibirica", kind:"animal", emoji:"🦡", color:"#c58a4a",
    habitat:"城郊、河岸、林灌丛", status:"常见小型食肉兽", rarity:2,
    desc:"俗称“黄鼠狼”，体细长、毛棕黄，动作敏捷。夜间捕食鼠类与昆虫，对控制城郊鼠患有益，是被误解的生态卫士。",
    facts:["“黄鼠狼给鸡拜年”其实主食是老鼠","受威胁时能释放臭腺自卫","身体细长，可钻入狭小洞穴追猎"], query:"siberian weasel" },
  { id:"civet", name:"果子狸", latin:"Paguma larvata", kind:"animal", emoji:"🐾", color:"#8a7566",
    habitat:"杭州西部山林、林缘", status:"国家“三有”保护动物", rarity:3,
    desc:"面部有一道白色纵纹的夜行小兽，善于爬树，爱吃野果，能帮助传播种子。栖于杭州周边的山林地带。",
    facts:["脸部的白色纵纹是识别特征","以野果为食，是天然的“播种者”","夜行性，白天多藏于树洞或岩缝"], query:"masked palm civet" },
  { id:"leopardcat", name:"豹猫", latin:"Prionailurus bengalensis", kind:"animal", emoji:"🐆", color:"#c79a5b",
    habitat:"杭州西部山林、灌丛", status:"国家二级保护动物", rarity:4,
    desc:"体型似家猫、周身缀满深色斑点的野生小型猫科动物。夜间独行捕猎鼠类与鸟类，是山林生态链中重要的中小型掠食者。",
    facts:["全身豹纹状斑点，故名豹猫","夜行独居，领域意识强","是控制山林鼠类数量的关键捕食者"], query:"leopard cat" },
  { id:"muntjac", name:"小麂", latin:"Muntiacus reevesi", kind:"animal", emoji:"🦌", color:"#a9743f",
    habitat:"杭州西部丘陵灌丛", status:"国家“三有”保护动物", rarity:3,
    desc:"体型娇小的鹿科动物，受惊时发出似犬吠的叫声，又称“黄麂”。喜独居于茂密灌丛，是江南丘陵常见的小型有蹄类。",
    facts:["受惊时叫声似狗吠，俗称“吠鹿”","雄性有短角与外露的獠牙状犬齿","多单独活动，性情机警隐秘"], query:"reeves muntjac" },
  { id:"toad", name:"中华蟾蜍", latin:"Bufo gargarizans", kind:"animal", emoji:"🐸", color:"#7d7a53",
    habitat:"稻田、池塘、林下湿地", status:"常见两栖动物", rarity:1,
    desc:"皮肤粗糙布满疣粒的大型蟾蜍，夜间大量捕食害虫，是农田天然的“除虫能手”。繁殖季会集群回到水塘产下长串卵带。",
    facts:["一只成蟾一夜可吃掉上百只害虫","耳后腺能分泌白色毒液自卫","卵呈长带状缠绕在水草间"], query:"asiatic toad" },
  { id:"frog", name:"黑斑侧褶蛙", latin:"Pelophylax nigromaculatus", kind:"animal", emoji:"🐸", color:"#6a8f4f",
    habitat:"稻田、荷塘、湿地", status:"国家“三有”保护动物", rarity:2,
    desc:"俗称“青蛙”“田鸡”，背部绿褐带黑斑，善跳善泳。以农田害虫为食，是稻作生态与水质健康的重要指示物种。",
    facts:["背侧一对明显的褶皱是识别特征","夏夜的“呱呱”合唱多来自雄蛙","蝌蚪期在水中，成体水陆两栖"], query:"black-spotted frog" },
  { id:"koi", name:"锦鲤", latin:"Cyprinus rubrofuscus", kind:"animal", emoji:"🐟", color:"#e2703a",
    habitat:"公园池塘、庭院水景", status:"观赏放养鱼类", rarity:1,
    desc:"由鲤鱼培育而来的观赏鱼，红白相间、色彩斑斓，常见于杭州各园林池塘，被视为吉祥与活力的象征。",
    facts:["由普通鲤鱼选育而成，寿命可达数十年","体色与花纹分为红白、大正、昭和等品系","记忆力不错，能认得投喂的人"], query:"koi carp" },
  { id:"mittencrab", name:"中华绒螯蟹", latin:"Eriocheir sinensis", kind:"animal", emoji:"🦀", color:"#7a6f57",
    habitat:"钱塘江、湖荡及入海河口", status:"本土洄游蟹类", rarity:2,
    desc:"即著名的“大闸蟹”，双螯密生绒毛。它需要在江河与河口之间洄游完成繁殖，是江南水乡重要的经济与生态物种。",
    facts:["螯上的浓密绒毛是名字由来","成蟹需洄游到河口咸淡水交界处产卵","是江南秋季最负盛名的时令水产"], query:"chinese mitten crab" },
  // ================= 植 物 (31-60) =================
  { id:"lotus", name:"荷花", latin:"Nelumbo nucifera", kind:"plant", emoji:"🪷", color:"#f4a6c0",
    habitat:"曲院风荷、西湖荷区", status:"西湖代表性水生植物", rarity:1,
    desc:"“接天莲叶无穷碧，映日荷花别样红”——荷花是西湖夏日的灵魂。它净化水体、为水生生物提供栖息，是杭州最经典的生态与人文符号。",
    facts:["荷叶“出淤泥不染”源于微米级绒毛结构","莲子可存活千年仍能发芽","曲院风荷是西湖十景之一"], query:"lotus flower" },
  { id:"osmanthus", name:"桂花", latin:"Osmanthus fragrans", kind:"plant", emoji:"🌼", color:"#e8b84b",
    habitat:"满觉陇、杭州全城行道", status:"杭州市花", rarity:1,
    desc:"金秋的杭州被桂花香浸透。作为杭州市花，桂花既是城市气味记忆，也是重要蜜源与文化植物，满觉陇的桂雨闻名遐迩。",
    facts:["杭州市花，秋日“满城尽带黄金甲”","花可制桂花糖、桂花酿","‘满陇桂雨’是新西湖十景之一"], query:"osmanthus flower" },
  { id:"camphor", name:"香樟", latin:"Cinnamomum camphora", kind:"plant", emoji:"🌳", color:"#6aa84f",
    habitat:"杭州行道树、庭院、山林", status:"杭州市树", rarity:1,
    desc:"香樟是杭州市树，四季常绿、树冠开阔，揉碎叶片有清凉樟脑香。它遍布城市街巷，是杭州“绿城”气质的骨架植物。",
    facts:["全株含樟脑，可驱虫","寿命可达数百年，多有古樟名木","杭州市树，撑起城市的绿荫天幕"], query:"camphor tree" },
  { id:"ginkgo", name:"银杏", latin:"Ginkgo biloba", kind:"plant", emoji:"🍂", color:"#e5c34a",
    habitat:"西湖景区、临安天目山", status:"孑遗植物 · 活化石", rarity:3,
    desc:"银杏是与恐龙同代的“活化石”，深秋满树金黄。天目山保存有古老银杏种群，杭州的秋日银杏大道更是市民热爱的赏秋去处。",
    facts:["现存最古老的种子植物之一","扇形叶脉呈二叉分支，十分独特","天目山有树龄逾千年的古银杏"], query:"ginkgo tree autumn" },
  { id:"tea", name:"龙井茶树", latin:"Camellia sinensis", kind:"plant", emoji:"🍵", color:"#8bbf5a",
    habitat:"龙井、梅家坞、狮峰山茶园", status:"杭州标志性经济作物", rarity:2,
    desc:"西湖龙井出自杭州连绵茶山。茶树喜温湿、耐酸性土壤，层层叠叠的茶园本身也是稳定水土、涵养生态的绿色屏障。",
    facts:["西湖龙井位列中国十大名茶","‘明前茶’指清明前采摘的嫩芽","狮、龙、云、虎、梅为传统五大核心产区"], query:"tea plant leaves" },
  { id:"metasequoia", name:"水杉", latin:"Metasequoia glyptostroboides", kind:"plant", emoji:"🌲", color:"#7ba05b",
    habitat:"西溪湿地、太子湾公园", status:"国家一级保护植物 · 活化石", rarity:4,
    desc:"水杉曾被认为已灭绝，直到上世纪在中国被重新发现，堪称植物界的传奇。西溪湿地成排的水杉秋来一片赤红，是杭州经典生态景观。",
    facts:["被称为“植物界的大熊猫”","落叶针叶树，秋季叶色由绿转红褐","西溪湿地的水杉林是热门观景点"], query:"metasequoia tree" },
  { id:"waterlily", name:"睡莲", latin:"Nymphaea", kind:"plant", emoji:"🌸", color:"#e6a9c9",
    habitat:"西湖、公园水景池塘", status:"常见水生观赏植物", rarity:1,
    desc:"叶片平铺水面、花朵贴近水面开放，与挺出水面的荷花不同。花多在白昼开放、傍晚闭合，是园林水景的常客。",
    facts:["花与叶多浮于水面，区别于荷花的“出水”","不少品种昼开夜合","莫奈笔下的名画主角正是睡莲"], query:"water lily" },
  { id:"willow", name:"垂柳", latin:"Salix babylonica", kind:"plant", emoji:"🌿", color:"#8fbf6a",
    habitat:"苏堤、白堤、西湖沿岸", status:"西湖标志性行道树", rarity:1,
    desc:"“柳浪闻莺”里的主角。细长柔软的枝条垂拂水面，早春最先吐绿，是西湖“一株杨柳一株桃”经典景致的重要组成。",
    facts:["‘柳浪闻莺’是西湖十景之一","早春最先萌芽，被视为报春之树","枝条柔韧，古人有“折柳送别”之俗"], query:"weeping willow" },
  { id:"plum", name:"梅", latin:"Prunus mume", kind:"plant", emoji:"🌸", color:"#e8a7b8",
    habitat:"灵峰、孤山、西溪梅林", status:"杭州传统名花", rarity:2,
    desc:"“疏影横斜水清浅，暗香浮动月黄昏”——梅在早春凌寒开放，杭州灵峰探梅久负盛名，是文人推崇的“岁寒”意象。",
    facts:["“灵峰探梅”是杭州赏梅胜地","早春先花后叶，凌寒而开","与松、竹并称“岁寒三友”"], query:"plum blossom" },
  { id:"peach", name:"桃", latin:"Prunus persica", kind:"plant", emoji:"🌸", color:"#f2a6b3",
    habitat:"苏堤、白堤、太子湾", status:"西湖春景代表", rarity:1,
    desc:"“桃红柳绿”是西湖春天的底色。苏堤沿岸桃柳相间，粉色花海与嫩绿柳丝交织，构成杭州最广为人知的春日画面。",
    facts:["苏堤“一株杨柳一株桃”闻名遐迩","先花后叶，花色由粉到红","果实即常见的水果桃子"], query:"peach blossom" },
  { id:"cherry", name:"樱花", latin:"Prunus serrulata", kind:"plant", emoji:"🌸", color:"#f4b8cf",
    habitat:"太子湾公园、植物园", status:"春季观赏名花", rarity:1,
    desc:"太子湾公园的樱花是杭州春天的热门打卡点。花开时节，粉白花瓣如云似雪，与郁金香花田相映成盛景。",
    facts:["太子湾是杭州著名的赏樱地","花期短暂，盛放仅约一周","花瓣随风飘落形成“樱吹雪”"], query:"cherry blossom" },
  { id:"magnolia", name:"玉兰", latin:"Magnolia denudata", kind:"plant", emoji:"🌷", color:"#eae0d5",
    habitat:"公园、庭院、行道", status:"早春观赏乔木", rarity:1,
    desc:"又称白玉兰，早春先花后叶，硕大洁白的花朵开满枝头，如玉盏高擎，是杭州庭园里报春的经典乔木。",
    facts:["先开花后长叶，满树皆花","花大而洁白，被喻为“玉树琼花”","是上海市市花"], query:"yulan magnolia" },
  { id:"camellia", name:"山茶", latin:"Camellia japonica", kind:"plant", emoji:"🌺", color:"#e0607e",
    habitat:"公园、庭院、林下", status:"冬春观赏名花", rarity:1,
    desc:"叶片浓绿光亮，冬春之交绽放红艳花朵，花期长、耐寒。与龙井茶同属山茶属，是杭州冬日园林的一抹暖色。",
    facts:["与茶树同属山茶属","冬春开花，花期可持续数月","凋谢时整朵花坠落而非散瓣"], query:"camellia japonica flower" },
  { id:"azalea", name:"杜鹃", latin:"Rhododendron simsii", kind:"plant", emoji:"🌸", color:"#e8567b",
    habitat:"山林坡地、公园花境", status:"春季观赏灌木", rarity:1,
    desc:"又名映山红，暮春时节漫山遍野的红花如火如霞。它是江南丘陵春景的代表，也是杭州园林中常见的观花灌木。",
    facts:["俗称“映山红”，花开成片如火","是长江以南山坡的常见野花","品种繁多，园艺栽培色彩丰富"], query:"azalea rhododendron" },
  { id:"reed", name:"芦苇", latin:"Phragmites australis", kind:"plant", emoji:"🌾", color:"#c9b072",
    habitat:"西溪湿地、钱塘江滩", status:"重要湿地植物", rarity:1,
    desc:"秋日西溪的芦花如雪，随风起伏成海。芦苇根系发达，能固岸护堤、净化水质，是湿地生态系统的基石植物之一。",
    facts:["‘秋雪庵’赏芦花是西溪一绝","根系可吸附污染物，净化水体","为众多水鸟提供隐蔽的栖息地"], query:"reed phragmites" },
  { id:"sweetflag", name:"菖蒲", latin:"Acorus calamus", kind:"plant", emoji:"🌿", color:"#6fae5c",
    habitat:"溪畔、池塘边、湿地", status:"传统水岸植物", rarity:1,
    desc:"剑形叶片挺立于水岸，全株有清香。端午时节与艾草一同悬于门前，是兼具文化寓意与水质净化功能的水生植物。",
    facts:["端午“挂菖蒲”是传统习俗","叶形似剑，故又称“水剑”","常用于水岸绿化与湿地修复"], query:"acorus calamus" },
  { id:"wisteria", name:"紫藤", latin:"Wisteria sinensis", kind:"plant", emoji:"💜", color:"#9b7cc4",
    habitat:"公园廊架、庭院", status:"春季观赏藤本", rarity:1,
    desc:"暮春时节，一串串紫色花穗自藤架垂落如帘，清香袭人。紫藤攀援生长，是杭州园林中营造花廊花架的经典藤本植物。",
    facts:["花序成串下垂，如紫色瀑布","是缠绕性藤本，寿命可达百年","常被用于搭建遮荫的花廊"], query:"chinese wisteria" },
  { id:"soapberry", name:"无患子", latin:"Sapindus mukorossi", kind:"plant", emoji:"🌳", color:"#8fae5a",
    habitat:"山林、行道、庭院", status:"乡土落叶乔木", rarity:2,
    desc:"秋季叶色金黄的落叶大乔木，果实富含天然皂苷，古人用来洗涤，是名副其实的“天然肥皂树”。",
    facts:["果皮含皂苷，古时用作洗涤剂","黑色圆润的种子可做念珠","秋叶金黄，是优良的乡土色叶树"], query:"sapindus mukorossi tree" },
  { id:"sweetgum", name:"枫香", latin:"Liquidambar formosana", kind:"plant", emoji:"🍁", color:"#d96f3a",
    habitat:"杭州西部山林、公园", status:"秋色叶乔木", rarity:2,
    desc:"“停车坐爱枫林晚”中的“枫”多指枫香。深秋叶片由绿转红、层林尽染，是江南山地最壮观的秋色来源之一。",
    facts:["古诗中的“霜叶红于二月花”多指枫香","叶三裂，与鸡爪槭的掌状多裂不同","果实为带刺的球状蒴果"], query:"liquidambar formosana autumn" },
  { id:"maple", name:"鸡爪槭", latin:"Acer palmatum", kind:"plant", emoji:"🍁", color:"#d9533b",
    habitat:"公园、庭院、九溪", status:"经典观叶乔木", rarity:2,
    desc:"叶片掌状深裂如鸡爪，秋来红艳似火。它是江南园林造景的“红叶主角”，杭州九溪、植物园的秋色离不开它。",
    facts:["叶掌状 5~9 深裂，形如鸡爪","园艺品种繁多，叶色红绿各异","是日式与江南庭园的常用树种"], query:"japanese maple acer palmatum" },
  { id:"grandmagnolia", name:"广玉兰", latin:"Magnolia grandiflora", kind:"plant", emoji:"🌼", color:"#e8e2d0",
    habitat:"行道、庭院、校园", status:"常绿观赏乔木", rarity:1,
    desc:"又称荷花玉兰，四季常绿，初夏开出硕大洁白、芳香馥郁的花朵。叶大而革质、背面锈色，是常见的庭荫与行道树。",
    facts:["花大如荷，故又名“荷花玉兰”","常绿乔木，叶背有锈色绒毛","原产北美，现广植于江南"], query:"magnolia grandiflora flower" },
  { id:"hibiscus", name:"木芙蓉", latin:"Hibiscus mutabilis", kind:"plant", emoji:"🌺", color:"#e987a6",
    habitat:"水岸、庭院、公园", status:"秋季观赏花木", rarity:1,
    desc:"深秋临水而开的大型花木，花朵一日之内由白转粉再变红，故有“三醉芙蓉”之称，是江南水边极富变化的应景花卉。",
    facts:["花色一日三变，人称“醉芙蓉”","晚秋开花，为萧瑟季节增色","成都又称“蓉城”即因此花"], query:"hibiscus mutabilis flower" },
  { id:"gardenia", name:"栀子", latin:"Gardenia jasminoides", kind:"plant", emoji:"🤍", color:"#e9e4d4",
    habitat:"庭院、绿篱、行道", status:"初夏芳香花木", rarity:1,
    desc:"初夏绽放的洁白花朵，香气清甜浓郁，绿叶油亮四季常青。是江南庭院与街巷常见的香花灌木，也可入药、作染料。",
    facts:["花香浓郁，是初夏的“气味标志”","果实古称“栀子”，可作黄色染料","叶片终年常绿，光泽油亮"], query:"gardenia jasminoides flower" },
  { id:"wintersweet", name:"蜡梅", latin:"Chimonanthus praecox", kind:"plant", emoji:"💛", color:"#e8c14a",
    habitat:"庭院、公园、灵峰", status:"冬季芳香花木", rarity:2,
    desc:"隆冬至早春开放的黄色小花，质感如蜡、清香扑鼻。它在百花凋零时独自绽放，与梅并称，为杭州的寒冬增添暖意与幽香。",
    facts:["与蔷薇科的“梅”并非同科植物","花瓣质感似蜜蜡，故名蜡梅","严冬先花后叶，暗香尤浓"], query:"wintersweet chimonanthus" },
  { id:"bamboo", name:"毛竹", latin:"Phyllostachys edulis", kind:"plant", emoji:"🎋", color:"#6fae5c",
    habitat:"临安、余杭山区竹海", status:"重要经济与生态竹种", rarity:1,
    desc:"江南最重要的大型竹种，成片竹海苍翠壮观。毛竹生长极快、固碳能力强，笋可食、竿可用，是山区兼具生态与经济价值的植物。",
    facts:["出笋期一昼夜可长高近一米","地下竹鞭相连，一片竹林常是同一克隆","是优良的固碳与水土保持植物"], query:"moso bamboo forest" },
  { id:"spiderlily", name:"石蒜", latin:"Lycoris radiata", kind:"plant", emoji:"🌺", color:"#e0433f",
    habitat:"林下、溪畔、墓地边坡", status:"秋季野生球根花卉", rarity:2,
    desc:"又名红花石蒜、彼岸花。秋日里花叶不相见——先抽出鲜红卷曲的花朵，花谢后才长叶，是江南阴湿林下极具特色的球根植物。",
    facts:["“花开叶落、叶生花谢”，花叶永不相见","俗称彼岸花，鳞茎有毒","多生于林缘、溪畔的阴湿处"], query:"red spider lily lycoris" },
  { id:"watercaltrop", name:"菱", latin:"Trapa natans", kind:"plant", emoji:"🌿", color:"#6a9a55",
    habitat:"西湖、池塘、静水河荡", status:"传统水生作物", rarity:1,
    desc:"叶片呈菱形莲座状浮于水面，果实即可食的“菱角”。江南采菱是延续千年的水乡风物，菱盘也为水生生物提供庇护。",
    facts:["“江南可采莲”里也常伴采菱","果实即菱角，两角或四角","叶柄中空膨大，助其浮于水面"], query:"water caltrop trapa" },
  { id:"iris", name:"鸢尾", latin:"Iris tectorum", kind:"plant", emoji:"💠", color:"#8f7cc9",
    habitat:"水岸、花境、湿地公园", status:"春季观赏与护岸植物", rarity:1,
    desc:"剑形叶片丛生，暮春开出蓝紫色蝶形花朵，花瓣上有精致的鸡冠状附属物。常用于水岸绿化，兼具观赏与固岸作用。",
    facts:["花瓣中央有鸡冠状突起，故称“蓝蝴蝶”","叶片剑形直立，成丛生长","常植于水边，可稳固岸坡"], query:"iris tectorum flower" },
  { id:"euryale", name:"芡实", latin:"Euryale ferox", kind:"plant", emoji:"🪷", color:"#5f8f6a",
    habitat:"西湖、湖荡、静水塘", status:"传统水生作物", rarity:2,
    desc:"叶片巨大如盘、布满尖刺浮于水面，花果带刺。其种仁即“芡实（鸡头米）”，是江南著名的水八仙之一，也是湿地的特色植物。",
    facts:["圆盘状大叶可达一米以上","种仁“鸡头米”是江南时令珍味","全株多刺，是其自我保护的方式"], query:"euryale ferox leaves" },
  { id:"planetree", name:"悬铃木", latin:"Platanus × acerifolia", kind:"plant", emoji:"🌳", color:"#8a9a5b",
    habitat:"城市主干道行道树", status:"城市行道树骨干", rarity:1,
    desc:"俗称“法国梧桐”，树冠高大浓密，是杭州许多老街的绿荫主角。秋季叶片金黄飘落，果实呈悬挂的小铃球，故名悬铃木。",
    facts:["俗称法国梧桐，其实是杂交种","果实似小铃悬挂枝头，故名","树皮呈斑驳片状剥落"], query:"london plane tree" }
];

// 供其它模块访问
window.SPECIES = SPECIES;
