/**
 * 物种图片索引（共 60 项，已逐一视觉校验）
 * ------------------------------------------------------------------
 * SPECIES_IMAGES        本地图片（assets/img/<id>.jpg，最长边 800px JPEG）
 * SPECIES_IMAGES_REMOTE 原始出处（维基百科 / Wikimedia Commons），仅作离线兜底
 * 取图顺序见 js/ai.js 的 imageUrlsFor()：本地 → 远程 → 关键词检索 → emoji
 * 本地文件由 tools/fetch-images.mjs + tools/downloader.html 生成。
 * ------------------------------------------------------------------
 */
window.SPECIES_IMAGES = {
  egret: "assets/img/egret.jpg",
  mandarin: "assets/img/mandarin.jpg",
  squirrel: "assets/img/squirrel.jpg",
  sturgeon: "assets/img/sturgeon.jpg",
  pheasant: "assets/img/pheasant.jpg",
  beeeater: "assets/img/beeeater.jpg",
  grebe: "assets/img/grebe.jpg",
  nightheron: "assets/img/nightheron.jpg",
  pondheron: "assets/img/pondheron.jpg",
  bulbul: "assets/img/bulbul.jpg",
  blackbird: "assets/img/blackbird.jpg",
  dove: "assets/img/dove.jpg",
  kingfisher: "assets/img/kingfisher.jpg",
  wagtail: "assets/img/wagtail.jpg",
  moorhen: "assets/img/moorhen.jpg",
  coot: "assets/img/coot.jpg",
  hoopoe: "assets/img/hoopoe.jpg",
  greattit: "assets/img/greattit.jpg",
  azuremagpie: "assets/img/azuremagpie.jpg",
  magpie: "assets/img/magpie.jpg",
  starling: "assets/img/starling.jpg",
  mallard: "assets/img/mallard.jpg",
  weasel: "assets/img/weasel.jpg",
  civet: "assets/img/civet.jpg",
  leopardcat: "assets/img/leopardcat.jpg",
  muntjac: "assets/img/muntjac.jpg",
  toad: "assets/img/toad.jpg",
  frog: "assets/img/frog.jpg",
  koi: "assets/img/koi.jpg",
  mittencrab: "assets/img/mittencrab.jpg",
  lotus: "assets/img/lotus.jpg",
  osmanthus: "assets/img/osmanthus.jpg",
  camphor: "assets/img/camphor.jpg",
  ginkgo: "assets/img/ginkgo.jpg",
  tea: "assets/img/tea.jpg",
  metasequoia: "assets/img/metasequoia.jpg",
  waterlily: "assets/img/waterlily.jpg",
  willow: "assets/img/willow.jpg",
  plum: "assets/img/plum.jpg",
  peach: "assets/img/peach.jpg",
  cherry: "assets/img/cherry.jpg",
  magnolia: "assets/img/magnolia.jpg",
  camellia: "assets/img/camellia.jpg",
  azalea: "assets/img/azalea.jpg",
  reed: "assets/img/reed.jpg",
  sweetflag: "assets/img/sweetflag.jpg",
  wisteria: "assets/img/wisteria.jpg",
  soapberry: "assets/img/soapberry.jpg",
  sweetgum: "assets/img/sweetgum.jpg",
  maple: "assets/img/maple.jpg",
  grandmagnolia: "assets/img/grandmagnolia.jpg",
  hibiscus: "assets/img/hibiscus.jpg",
  gardenia: "assets/img/gardenia.jpg",
  wintersweet: "assets/img/wintersweet.jpg",
  bamboo: "assets/img/bamboo.jpg",
  spiderlily: "assets/img/spiderlily.jpg",
  watercaltrop: "assets/img/watercaltrop.jpg",
  iris: "assets/img/iris.jpg",
  euryale: "assets/img/euryale.jpg",
  planetree: "assets/img/planetree.jpg"
};

/* 原始出处（Wikimedia），本地图缺失时兜底 */
window.SPECIES_IMAGES_REMOTE = {
  egret: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Little_egret_%28Egretta_garzetta%29_Photograph_by_Shantanu_Kuveskar.jpg",
  mandarin: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Pair_of_mandarin_ducks.jpg/960px-Pair_of_mandarin_ducks.jpg",
  squirrel: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Pallas%27s_squirrel_%28Callosciurus_erythraeus_thaiwanensis%29_Qianshan.jpg/960px-Pallas%27s_squirrel_%28Callosciurus_erythraeus_thaiwanensis%29_Qianshan.jpg",
  sturgeon: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Shanghai_zoo_-_Acipenser_sinensis.jpg/960px-Shanghai_zoo_-_Acipenser_sinensis.jpg",
  pheasant: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Lophura_nycthemera_-Mauritius_-male-8a.jpg/960px-Lophura_nycthemera_-Mauritius_-male-8a.jpg",
  beeeater: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Blue-throated_bee-eater_%28Merops_viridis%29.jpg/960px-Blue-throated_bee-eater_%28Merops_viridis%29.jpg",
  grebe: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Little_grebe_Zwergtaucher.jpg/960px-Little_grebe_Zwergtaucher.jpg",
  nightheron: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Nycticorax_nycticorax_457953189.jpg/960px-Nycticorax_nycticorax_457953189.jpg",
  pondheron: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Chinese_Pond_Heron_in_Summer.jpg/960px-Chinese_Pond_Heron_in_Summer.jpg",
  bulbul: "https://upload.wikimedia.org/wikipedia/commons/6/66/Light-vented_Bulbul2.jpg",
  blackbird: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Turdus_merula_mandarinus_Hong_Kong_6.jpg/960px-Turdus_merula_mandarinus_Hong_Kong_6.jpg",
  dove: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Spilopelia_chinensis_Zhengzhou_20220915%2C_crop.jpg/960px-Spilopelia_chinensis_Zhengzhou_20220915%2C_crop.jpg",
  kingfisher: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Alcedo_atthis_-England-8_%28cropped%29.jpg/960px-Alcedo_atthis_-England-8_%28cropped%29.jpg",
  wagtail: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/20180415_015_Winterswijk_Witte_kwikstaart_%2840785272624%29.jpg/960px-20180415_015_Winterswijk_Witte_kwikstaart_%2840785272624%29.jpg",
  moorhen: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Common_moorhen_%28Gallinula_chloropus%29_France.jpg/960px-Common_moorhen_%28Gallinula_chloropus%29_France.jpg",
  coot: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Eurasian_Coot_2023_11_25_03.jpg/960px-Eurasian_Coot_2023_11_25_03.jpg",
  hoopoe: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Israel._Eurasian_Hoopoe_%286497645007%29.jpg/960px-Israel._Eurasian_Hoopoe_%286497645007%29.jpg",
  greattit: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Cinereous_tit_%28Parus_cinereus%29_Photograph_by_Shantanu_Kuveskar.jpg",
  azuremagpie: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/2022-07-18_Azure-winged_Magpie%2C_Zhengzhou%2C_Henan%2C_China_%28cropped%29.jpg/960px-2022-07-18_Azure-winged_Magpie%2C_Zhengzhou%2C_Henan%2C_China_%28cropped%29.jpg",
  magpie: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Korean_magpie_in_Daejeon_%28side_profile%29.jpg/960px-Korean_magpie_in_Daejeon_%28side_profile%29.jpg",
  starling: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Black-collared_starling_%28Gracupica_nigricollis%29.jpg/960px-Black-collared_starling_%28Gracupica_nigricollis%29.jpg",
  mallard: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Anas_platyrhynchos_male_female_quadrat.jpg/960px-Anas_platyrhynchos_male_female_quadrat.jpg",
  weasel: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Siberian_Weasel_Pangolakha_Wildlife_Sanctuary_East_Sikkim_India_14.05.2016.jpg",
  civet: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Palm_civet_on_tree_%28detail%29.jpg/960px-Palm_civet_on_tree_%28detail%29.jpg",
  leopardcat: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Prionailurus_bengalensis_bengalensis_2-D%C3%A9coupe.JPG/960px-Prionailurus_bengalensis_bengalensis_2-D%C3%A9coupe.JPG",
  muntjac: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Chinesischer_Muntjak_Muntiacus_reevesi_Zoo_Augsburg-04.jpg/960px-Chinesischer_Muntjak_Muntiacus_reevesi_Zoo_Augsburg-04.jpg",
  toad: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Bufo_gargarizans_profile.jpg/960px-Bufo_gargarizans_profile.jpg",
  frog: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Pelophylax_nigromaculatus_s1.JPG/960px-Pelophylax_nigromaculatus_s1.JPG",
  koi: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Ojiya_Nishikigoi_no_Sato_ac_%283%29.jpg/960px-Ojiya_Nishikigoi_no_Sato_ac_%283%29.jpg",
  mittencrab: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/EriocheirSinensis1.jpg/960px-EriocheirSinensis1.jpg",
  lotus: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Sacred_lotus_Nelumbo_nucifera.jpg/960px-Sacred_lotus_Nelumbo_nucifera.jpg",
  osmanthus: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Osmanthus_fragrans_%28orange_flowers%29.jpg/960px-Osmanthus_fragrans_%28orange_flowers%29.jpg",
  camphor: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Cinnamomum_camphora20050314.jpg",
  ginkgo: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/GINKGOBAUM-2.jpg/960px-GINKGOBAUM-2.jpg",
  tea: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Csinensis.jpg/960px-Csinensis.jpg",
  metasequoia: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Metasequoia_glyptostroboides_in_Forest_park_of_Aichi_Prefecture.jpg/960px-Metasequoia_glyptostroboides_in_Forest_park_of_Aichi_Prefecture.jpg",
  waterlily: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Nymphaea_alba.001_-_Breendonk.jpg/960px-Nymphaea_alba.001_-_Breendonk.jpg",
  willow: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Ch%C3%A2teau_de_Chenonceau_-_jardin_Russell-Page_%2801%29.jpg/960px-Ch%C3%A2teau_de_Chenonceau_-_jardin_Russell-Page_%2801%29.jpg",
  plum: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Prunus_mume.JPG/960px-Prunus_mume.JPG",
  peach: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Prunus_persica_flw.jpg/960px-Prunus_persica_flw.jpg",
  cherry: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Cerisier_du_Japon_Prunus_serrulata.jpg/960px-Cerisier_du_Japon_Prunus_serrulata.jpg",
  magnolia: "https://upload.wikimedia.org/wikipedia/commons/6/62/Yulan_1.JPG",
  camellia: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Camellia_japonica_NBG.jpg/960px-Camellia_japonica_NBG.jpg",
  azalea: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Rhododendron_simsii-bunga_2-Lany_pirna.jpg/960px-Rhododendron_simsii-bunga_2-Lany_pirna.jpg",
  reed: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Phragmites_australis_-_NASA_Tracks_an_Environmental_Invader_%2848049936657%29.jpg/960px-Phragmites_australis_-_NASA_Tracks_an_Environmental_Invader_%2848049936657%29.jpg",
  sweetflag: "https://upload.wikimedia.org/wikipedia/commons/3/37/Acorus_calamus1.jpg",
  wisteria: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Chinesischer_Blauregen_Detail_Bl%C3%BCtentraube.JPG/960px-Chinesischer_Blauregen_Detail_Bl%C3%BCtentraube.JPG",
  soapberry: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Sapindus_mukorossi2.jpg/960px-Sapindus_mukorossi2.jpg",
  sweetgum: "https://upload.wikimedia.org/wikipedia/commons/4/4e/Liquidambar_formosana_01.jpg",
  maple: "https://upload.wikimedia.org/wikipedia/commons/d/d6/Acer_palmatum0.jpg",
  grandmagnolia: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Magn%C3%B2lia_a_Verbania.JPG/960px-Magn%C3%B2lia_a_Verbania.JPG",
  hibiscus: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Mufurong1.jpg/960px-Mufurong1.jpg",
  gardenia: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Gardenia_jasminoides_flower_Argentina.jpg/960px-Gardenia_jasminoides_flower_Argentina.jpg",
  wintersweet: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Chimonanthus_praecox_%2818248235374%29.jpg/960px-Chimonanthus_praecox_%2818248235374%29.jpg",
  bamboo: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Bamboo_forest.jpg",
  spiderlily: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Lycoris_radiata_Higanbana_in_a_woods.jpg/960px-Lycoris_radiata_Higanbana_in_a_woods.jpg",
  watercaltrop: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Trapa_natans_kz6.JPG/960px-Trapa_natans_kz6.JPG",
  iris: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Iris_tectorum_01.JPG/960px-Iris_tectorum_01.JPG",
  euryale: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Junicho-Gata_lagoon_Euryale_feroxe_habitat_07.jpg/960px-Junicho-Gata_lagoon_Euryale_feroxe_habitat_07.jpg",
  planetree: "https://upload.wikimedia.org/wikipedia/commons/2/23/Berkeley_Square_-_geograph.org.uk_-_911963.jpg"
};
